### ISSUE TITLE
Add additional user meta-data to mini profile and main profile page

### ISSUE THREAD

**Issue by Blakeinstein** [Upvision/community-front-end#2]
part of Upvision/community-back-end#3

Most details need to be implemented on front end as well.

- [ ] Year (Current active year, to be dynamically calculated. Inclusive of Alumni)
- [ ] Tenure (Years spent in college, may not be 4/2 years provided year backs)
- [ ] A list of user editable experiences.

Move suggestions to the linked issue on the back-end repo.
